// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        (unknown)
// source: grpc/skill.proto

package skillpb

// ExecuteRequest is sent by Atlas to execute a node
type ExecuteRequest struct {
	NodeId   string              `json:"nodeId,omitempty"`
	NodeType string              `json:"nodeType,omitempty"`
	Config   map[string][]byte   `json:"config,omitempty"`
	Input    map[string][]byte   `json:"input,omitempty"`
	Context  *ExecutionContext   `json:"context,omitempty"`
}

// ExecutionContext provides runtime information
type ExecutionContext struct {
	RunId     string            `json:"runId,omitempty"`
	AgentId   string            `json:"agentId,omitempty"`
	Namespace string            `json:"namespace,omitempty"`
	Variables map[string]string `json:"variables,omitempty"`
}

// ExecuteResponse is returned by the skill
type ExecuteResponse struct {
	Output   map[string][]byte `json:"output,omitempty"`
	Error    *Error            `json:"error,omitempty"`
	NextStep string            `json:"nextStep,omitempty"`
}

// Error represents an execution error
type Error struct {
	Message string            `json:"message,omitempty"`
	Type    string            `json:"type,omitempty"`
	Details map[string]string `json:"details,omitempty"`
}

// GetNodeTypesRequest
type GetNodeTypesRequest struct{}

// GetNodeTypesResponse
type GetNodeTypesResponse struct {
	NodeTypes []string `json:"nodeTypes,omitempty"`
}

// GetNodeSchemaRequest
type GetNodeSchemaRequest struct {
	NodeType string `json:"nodeType,omitempty"`
}

// GetNodeSchemaResponse
type GetNodeSchemaResponse struct {
	Schema []byte `json:"schema,omitempty"`
}

// HealthRequest
type HealthRequest struct{}

// HealthResponse
type HealthResponse struct {
	Healthy bool   `json:"healthy,omitempty"`
	SkillId string `json:"skillId,omitempty"`
	Version string `json:"version,omitempty"`
}