// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        (unknown)
// source: grpc/skill.proto

package skillpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

const (
	SkillService_Execute_FullMethodName     = "/axiom.skill.v1.SkillService/Execute"
	SkillService_GetNodeTypes_FullMethodName = "/axiom.skill.v1.SkillService/GetNodeTypes"
	SkillService_GetNodeSchema_FullMethodName = "/axiom.skill.v1.SkillService/GetNodeSchema"
	SkillService_Health_FullMethodName      = "/axiom.skill.v1.SkillService/Health"
)

// SkillServiceClient is the client API for SkillService service.
type SkillServiceClient interface {
	Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error)
	GetNodeTypes(ctx context.Context, in *GetNodeTypesRequest, opts ...grpc.CallOption) (*GetNodeTypesResponse, error)
	GetNodeSchema(ctx context.Context, in *GetNodeSchemaRequest, opts ...grpc.CallOption) (*GetNodeSchemaResponse, error)
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type skillServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSkillServiceClient(cc grpc.ClientConnInterface) SkillServiceClient {
	return &skillServiceClient{cc}
}

func (c *skillServiceClient) Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error) {
	out := new(ExecuteResponse)
	err := c.cc.Invoke(ctx, SkillService_Execute_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skillServiceClient) GetNodeTypes(ctx context.Context, in *GetNodeTypesRequest, opts ...grpc.CallOption) (*GetNodeTypesResponse, error) {
	out := new(GetNodeTypesResponse)
	err := c.cc.Invoke(ctx, SkillService_GetNodeTypes_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skillServiceClient) GetNodeSchema(ctx context.Context, in *GetNodeSchemaRequest, opts ...grpc.CallOption) (*GetNodeSchemaResponse, error) {
	out := new(GetNodeSchemaResponse)
	err := c.cc.Invoke(ctx, SkillService_GetNodeSchema_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skillServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, SkillService_Health_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SkillServiceServer is the server API for SkillService service.
type SkillServiceServer interface {
	Execute(context.Context, *ExecuteRequest) (*ExecuteResponse, error)
	GetNodeTypes(context.Context, *GetNodeTypesRequest) (*GetNodeTypesResponse, error)
	GetNodeSchema(context.Context, *GetNodeSchemaRequest) (*GetNodeSchemaResponse, error)
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
}

// UnimplementedSkillServer must be embedded to have forward compatible implementations.
type UnimplementedSkillServer struct{}

func (UnimplementedSkillServer) Execute(context.Context, *ExecuteRequest) (*ExecuteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedSkillServer) GetNodeTypes(context.Context, *GetNodeTypesRequest) (*GetNodeTypesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNodeTypes not implemented")
}
func (UnimplementedSkillServer) GetNodeSchema(context.Context, *GetNodeSchemaRequest) (*GetNodeSchemaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNodeSchema not implemented")
}
func (UnimplementedSkillServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}

// RegisterSkillServer registers a skill server
func RegisterSkillServer(s grpc.ServiceRegistrar, srv SkillServiceServer) {
	s.RegisterService(&SkillService_ServiceDesc, srv)
}

var SkillService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "axiom.skill.v1.SkillService",
	HandlerType: (*SkillServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Execute",
			Handler:    _SkillService_Execute_Handler,
		},
		{
			MethodName: "GetNodeTypes",
			Handler:    _SkillService_GetNodeTypes_Handler,
		},
		{
			MethodName: "GetNodeSchema",
			Handler:    _SkillService_GetNodeSchema_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _SkillService_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/skill.proto",
}

func _SkillService_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkillServiceServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkillService_Execute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkillServiceServer).Execute(ctx, req.(*ExecuteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkillService_GetNodeTypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeTypesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkillServiceServer).GetNodeTypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkillService_GetNodeTypes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkillServiceServer).GetNodeTypes(ctx, req.(*GetNodeTypesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkillService_GetNodeSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeSchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkillServiceServer).GetNodeSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkillService_GetNodeSchema_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkillServiceServer).GetNodeSchema(ctx, req.(*GetNodeSchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkillService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkillServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkillService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkillServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}