// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: skill.proto

package skillpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ExecuteRequest is sent by Atlas to execute a node
type ExecuteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Node identification
	NodeId   string `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	NodeType string `protobuf:"bytes,2,opt,name=node_type,json=nodeType,proto3" json:"node_type,omitempty"`
	// Node configuration (from the workflow definition)
	Config map[string][]byte `protobuf:"bytes,3,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Input data from previous node
	Input map[string][]byte `protobuf:"bytes,4,rep,name=input,proto3" json:"input,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Execution context
	Context *ExecutionContext `protobuf:"bytes,5,opt,name=context,proto3" json:"context,omitempty"`
	// Resolved bindings (connection strings, API keys, etc.)
	Bindings      map[string][]byte `protobuf:"bytes,6,rep,name=bindings,proto3" json:"bindings,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_skill_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skill_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_skill_proto_rawDescGZIP(), []int{0}
}

func (x *ExecuteRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ExecuteRequest) GetNodeType() string {
	if x != nil {
		return x.NodeType
	}
	return ""
}

func (x *ExecuteRequest) GetConfig() map[string][]byte {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *ExecuteRequest) GetInput() map[string][]byte {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *ExecuteRequest) GetContext() *ExecutionContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *ExecuteRequest) GetBindings() map[string][]byte {
	if x != nil {
		return x.Bindings
	}
	return nil
}

// ExecutionContext provides runtime information
type ExecutionContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Namespace     string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Variables     map[string]string      `protobuf:"bytes,4,rep,name=variables,proto3" json:"variables,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionContext) Reset() {
	*x = ExecutionContext{}
	mi := &file_skill_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionContext) ProtoMessage() {}

func (x *ExecutionContext) ProtoReflect() protoreflect.Message {
	mi := &file_skill_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionContext.ProtoReflect.Descriptor instead.
func (*ExecutionContext) Descriptor() ([]byte, []int) {
	return file_skill_proto_rawDescGZIP(), []int{1}
}

func (x *ExecutionContext) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *ExecutionContext) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ExecutionContext) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ExecutionContext) GetVariables() map[string]string {
	if x != nil {
		return x.Variables
	}
	return nil
}

// ExecuteResponse is returned by the skill
type ExecuteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Output data for next node
	Output map[string][]byte `protobuf:"bytes,1,rep,name=output,proto3" json:"output,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Error if execution failed
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// Next step for branching nodes (if, switch)
	NextStep      string `protobuf:"bytes,3,opt,name=next_step,json=nextStep,proto3" json:"next_step,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_skill_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_skill_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_skill_proto_rawDescGZIP(), []int{2}
}

func (x *ExecuteResponse) GetOutput() map[string][]byte {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *ExecuteResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *ExecuteResponse) GetNextStep() string {
	if x != nil {
		return x.NextStep
	}
	return ""
}

// Error represents an execution error
type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"` // "validation", "execution", "timeout", etc.
	Details       map[string]string      `protobuf:"bytes,3,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_skill_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_skill_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_skill_proto_rawDescGZIP(), []int{3}
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Error) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Error) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

// GetNodeTypesRequest
type GetNodeTypesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeTypesRequest) Reset() {
	*x = GetNodeTypesRequest{}
	mi := &file_skill_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeTypesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeTypesRequest) ProtoMessage() {}

func (x *GetNodeTypesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skill_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeTypesRequest.ProtoReflect.Descriptor instead.
func (*GetNodeTypesRequest) Descriptor() ([]byte, []int) {
	return file_skill_proto_rawDescGZIP(), []int{4}
}

// GetNodeTypesResponse
type GetNodeTypesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeTypes     []string               `protobuf:"bytes,1,rep,name=node_types,json=nodeTypes,proto3" json:"node_types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeTypesResponse) Reset() {
	*x = GetNodeTypesResponse{}
	mi := &file_skill_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeTypesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeTypesResponse) ProtoMessage() {}

func (x *GetNodeTypesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_skill_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeTypesResponse.ProtoReflect.Descriptor instead.
func (*GetNodeTypesResponse) Descriptor() ([]byte, []int) {
	return file_skill_proto_rawDescGZIP(), []int{5}
}

func (x *GetNodeTypesResponse) GetNodeTypes() []string {
	if x != nil {
		return x.NodeTypes
	}
	return nil
}

// GetNodeSchemaRequest
type GetNodeSchemaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeType      string                 `protobuf:"bytes,1,opt,name=node_type,json=nodeType,proto3" json:"node_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeSchemaRequest) Reset() {
	*x = GetNodeSchemaRequest{}
	mi := &file_skill_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeSchemaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeSchemaRequest) ProtoMessage() {}

func (x *GetNodeSchemaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skill_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeSchemaRequest.ProtoReflect.Descriptor instead.
func (*GetNodeSchemaRequest) Descriptor() ([]byte, []int) {
	return file_skill_proto_rawDescGZIP(), []int{6}
}

func (x *GetNodeSchemaRequest) GetNodeType() string {
	if x != nil {
		return x.NodeType
	}
	return ""
}

// GetNodeSchemaResponse
type GetNodeSchemaResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// JSON schema for the node configuration
	Schema        []byte `protobuf:"bytes,1,opt,name=schema,proto3" json:"schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeSchemaResponse) Reset() {
	*x = GetNodeSchemaResponse{}
	mi := &file_skill_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeSchemaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeSchemaResponse) ProtoMessage() {}

func (x *GetNodeSchemaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_skill_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeSchemaResponse.ProtoReflect.Descriptor instead.
func (*GetNodeSchemaResponse) Descriptor() ([]byte, []int) {
	return file_skill_proto_rawDescGZIP(), []int{7}
}

func (x *GetNodeSchemaResponse) GetSchema() []byte {
	if x != nil {
		return x.Schema
	}
	return nil
}

// HealthRequest
type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_skill_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skill_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_skill_proto_rawDescGZIP(), []int{8}
}

// HealthResponse
type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	SkillId       string                 `protobuf:"bytes,2,opt,name=skill_id,json=skillId,proto3" json:"skill_id,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_skill_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_skill_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_skill_proto_rawDescGZIP(), []int{9}
}

func (x *HealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthResponse) GetSkillId() string {
	if x != nil {
		return x.SkillId
	}
	return ""
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_skill_proto protoreflect.FileDescriptor

const file_skill_proto_rawDesc = "" +
	"\n" +
	"\vskill.proto\x12\x0eaxiom.skill.v1\"\x83\x04\n" +
	"\x0eExecuteRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1b\n" +
	"\tnode_type\x18\x02 \x01(\tR\bnodeType\x12B\n" +
	"\x06config\x18\x03 \x03(\v2*.axiom.skill.v1.ExecuteRequest.ConfigEntryR\x06config\x12?\n" +
	"\x05input\x18\x04 \x03(\v2).axiom.skill.v1.ExecuteRequest.InputEntryR\x05input\x12:\n" +
	"\acontext\x18\x05 \x01(\v2 .axiom.skill.v1.ExecutionContextR\acontext\x12H\n" +
	"\bbindings\x18\x06 \x03(\v2,.axiom.skill.v1.ExecuteRequest.BindingsEntryR\bbindings\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\x1a8\n" +
	"\n" +
	"InputEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\x1a;\n" +
	"\rBindingsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"\xef\x01\n" +
	"\x10ExecutionContext\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12M\n" +
	"\tvariables\x18\x04 \x03(\v2/.axiom.skill.v1.ExecutionContext.VariablesEntryR\tvariables\x1a<\n" +
	"\x0eVariablesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xdb\x01\n" +
	"\x0fExecuteResponse\x12C\n" +
	"\x06output\x18\x01 \x03(\v2+.axiom.skill.v1.ExecuteResponse.OutputEntryR\x06output\x12+\n" +
	"\x05error\x18\x02 \x01(\v2\x15.axiom.skill.v1.ErrorR\x05error\x12\x1b\n" +
	"\tnext_step\x18\x03 \x01(\tR\bnextStep\x1a9\n" +
	"\vOutputEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"\xaf\x01\n" +
	"\x05Error\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12<\n" +
	"\adetails\x18\x03 \x03(\v2\".axiom.skill.v1.Error.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x15\n" +
	"\x13GetNodeTypesRequest\"5\n" +
	"\x14GetNodeTypesResponse\x12\x1d\n" +
	"\n" +
	"node_types\x18\x01 \x03(\tR\tnodeTypes\"3\n" +
	"\x14GetNodeSchemaRequest\x12\x1b\n" +
	"\tnode_type\x18\x01 \x01(\tR\bnodeType\"/\n" +
	"\x15GetNodeSchemaResponse\x12\x16\n" +
	"\x06schema\x18\x01 \x01(\fR\x06schema\"\x0f\n" +
	"\rHealthRequest\"_\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x19\n" +
	"\bskill_id\x18\x02 \x01(\tR\askillId\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion2\xdc\x02\n" +
	"\fSkillService\x12J\n" +
	"\aExecute\x12\x1e.axiom.skill.v1.ExecuteRequest\x1a\x1f.axiom.skill.v1.ExecuteResponse\x12Y\n" +
	"\fGetNodeTypes\x12#.axiom.skill.v1.GetNodeTypesRequest\x1a$.axiom.skill.v1.GetNodeTypesResponse\x12\\\n" +
	"\rGetNodeSchema\x12$.axiom.skill.v1.GetNodeSchemaRequest\x1a%.axiom.skill.v1.GetNodeSchemaResponse\x12G\n" +
	"\x06Health\x12\x1d.axiom.skill.v1.HealthRequest\x1a\x1e.axiom.skill.v1.HealthResponseB1Z/github.com/axiom-studio/skills.sdk/grpc/skillpbb\x06proto3"

var (
	file_skill_proto_rawDescOnce sync.Once
	file_skill_proto_rawDescData []byte
)

func file_skill_proto_rawDescGZIP() []byte {
	file_skill_proto_rawDescOnce.Do(func() {
		file_skill_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_skill_proto_rawDesc), len(file_skill_proto_rawDesc)))
	})
	return file_skill_proto_rawDescData
}

var file_skill_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_skill_proto_goTypes = []any{
	(*ExecuteRequest)(nil),        // 0: axiom.skill.v1.ExecuteRequest
	(*ExecutionContext)(nil),      // 1: axiom.skill.v1.ExecutionContext
	(*ExecuteResponse)(nil),       // 2: axiom.skill.v1.ExecuteResponse
	(*Error)(nil),                 // 3: axiom.skill.v1.Error
	(*GetNodeTypesRequest)(nil),   // 4: axiom.skill.v1.GetNodeTypesRequest
	(*GetNodeTypesResponse)(nil),  // 5: axiom.skill.v1.GetNodeTypesResponse
	(*GetNodeSchemaRequest)(nil),  // 6: axiom.skill.v1.GetNodeSchemaRequest
	(*GetNodeSchemaResponse)(nil), // 7: axiom.skill.v1.GetNodeSchemaResponse
	(*HealthRequest)(nil),         // 8: axiom.skill.v1.HealthRequest
	(*HealthResponse)(nil),        // 9: axiom.skill.v1.HealthResponse
	nil,                           // 10: axiom.skill.v1.ExecuteRequest.ConfigEntry
	nil,                           // 11: axiom.skill.v1.ExecuteRequest.InputEntry
	nil,                           // 12: axiom.skill.v1.ExecuteRequest.BindingsEntry
	nil,                           // 13: axiom.skill.v1.ExecutionContext.VariablesEntry
	nil,                           // 14: axiom.skill.v1.ExecuteResponse.OutputEntry
	nil,                           // 15: axiom.skill.v1.Error.DetailsEntry
}
var file_skill_proto_depIdxs = []int32{
	10, // 0: axiom.skill.v1.ExecuteRequest.config:type_name -> axiom.skill.v1.ExecuteRequest.ConfigEntry
	11, // 1: axiom.skill.v1.ExecuteRequest.input:type_name -> axiom.skill.v1.ExecuteRequest.InputEntry
	1,  // 2: axiom.skill.v1.ExecuteRequest.context:type_name -> axiom.skill.v1.ExecutionContext
	12, // 3: axiom.skill.v1.ExecuteRequest.bindings:type_name -> axiom.skill.v1.ExecuteRequest.BindingsEntry
	13, // 4: axiom.skill.v1.ExecutionContext.variables:type_name -> axiom.skill.v1.ExecutionContext.VariablesEntry
	14, // 5: axiom.skill.v1.ExecuteResponse.output:type_name -> axiom.skill.v1.ExecuteResponse.OutputEntry
	3,  // 6: axiom.skill.v1.ExecuteResponse.error:type_name -> axiom.skill.v1.Error
	15, // 7: axiom.skill.v1.Error.details:type_name -> axiom.skill.v1.Error.DetailsEntry
	0,  // 8: axiom.skill.v1.SkillService.Execute:input_type -> axiom.skill.v1.ExecuteRequest
	4,  // 9: axiom.skill.v1.SkillService.GetNodeTypes:input_type -> axiom.skill.v1.GetNodeTypesRequest
	6,  // 10: axiom.skill.v1.SkillService.GetNodeSchema:input_type -> axiom.skill.v1.GetNodeSchemaRequest
	8,  // 11: axiom.skill.v1.SkillService.Health:input_type -> axiom.skill.v1.HealthRequest
	2,  // 12: axiom.skill.v1.SkillService.Execute:output_type -> axiom.skill.v1.ExecuteResponse
	5,  // 13: axiom.skill.v1.SkillService.GetNodeTypes:output_type -> axiom.skill.v1.GetNodeTypesResponse
	7,  // 14: axiom.skill.v1.SkillService.GetNodeSchema:output_type -> axiom.skill.v1.GetNodeSchemaResponse
	9,  // 15: axiom.skill.v1.SkillService.Health:output_type -> axiom.skill.v1.HealthResponse
	12, // [12:16] is the sub-list for method output_type
	8,  // [8:12] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_skill_proto_init() }
func file_skill_proto_init() {
	if File_skill_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_skill_proto_rawDesc), len(file_skill_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_skill_proto_goTypes,
		DependencyIndexes: file_skill_proto_depIdxs,
		MessageInfos:      file_skill_proto_msgTypes,
	}.Build()
	File_skill_proto = out.File
	file_skill_proto_goTypes = nil
	file_skill_proto_depIdxs = nil
}
